name: validate-powershell-scripts
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - shell: pwsh
        run: Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
      - shell: pwsh
        run: ${{ github.workspace }}\Invoke-Validation.ps1
